Support to spawn OCR processes over NUMA resources
- Currently only supported for SLURM and Intel MPI
- New 'numa' option to CFG generator
	- A ':' delimited string indicating the PD distribution policy,
	  the number of packages and the number of core per package.
	- The PD distribution policy describes how OCR processes are
	  distributed over resources in either round-robin or block
	  fashion. Respectively "RR" and "BLOCK"
	- The number of packages describes how many NUMA domains are
	  available on the targeted hardware
	- The number of core per package indicates how many computation
	  units are available per NUMA domain
	- The 'numa' option is to be used in conjunction with the 'binding'
	  option to provide a list of affinity binding that will be adjusted
	  per NUMA domain.
- OCR compile time CFLAGS 'SHOW_BINDING_INFO' turns on per OCR process
  print out of binding information at runtime.
- For a given OCR_NUM_NODES and numa domains declared in a cfg file,
  ocrrun will try to spawn OCR_NUM_NODES*NUMA_DOMAINS

Change-Id: I7995dbcda856a516a5f2171cb94c430ea5067ea9

diff --git a/ocr/build/x86-mpi/ocrrun_x86-mpi b/ocr/build/x86-mpi/ocrrun_x86-mpi
--- a/ocr/build/x86-mpi/ocrrun_x86-mpi
+++ b/ocr/build/x86-mpi/ocrrun_x86-mpi
@@ -1,6 +1,11 @@
 
 #!/bin/bash
 
+function checkSingleNuma() {
+    if [[ ! ((${OCRRUN_OPT_ENVKIND} == "SLURM") || (${OCRRUN_OPT_ENVKIND} == "impi")) ]]; then
+        echo "error: OCR_NUMA_FACTOR has not been tested with OCRRUN_OPT_ENVKIND= ${OCRRUN_OPT_ENVKIND} "
+    fi
+}
 
 # User-provided or generated
 PROGRAM_BIN=
@@ -10,8 +15,7 @@ if [[ ${OCRRUN_OPT_ENVKIND} == "mvapich" ]]; then
     OCRRUN_OPT_CMD=${OCRRUN_OPT_CMD-"mpirun"}
     OCRRUN_OPT_NUM_NODES=${OCRRUN_OPT_NUM_NODES-"-np"}
     OCRRUN_OPT_NODEFILE=${OCRRUN_OPT_NODEFILE-"-f"}
-elif [[ ${OCRRUN_OPT_ENVKIND} == "CLE" ]]; then
-    # Cray Linux Environment (CLE)
+elif [[ ${OCRRUN_OPT_ENVKIND} == "CLE" ]]; then # Cray Linux Environment (CLE)
     OCRRUN_OPT_CMD=${OCRRUN_OPT_CMD-"aprun"}
     # Default forces one mpi process per node
     OCRRUN_OPT_NUM_NODES=${OCRRUN_OPT_NUM_NODES-"-N 1 -n"}
@@ -100,20 +104,36 @@ if [[ "$RES" != "" ]]; then
         OCR_NUM_NODES=2
     fi
 
+    # Number of OCR PD / MPI ranks to collocate per cluster node
+    OCR_NUMA_FACTOR=`grep "numa[[:space:]]*=" ${OCR_CONFIG} | cut -d':' -f2-2`
+    if [ -z "${OCR_NUMA_FACTOR}" ]; then
+        OCR_NUMA_FACTOR=1
+    fi
+    checkSingleNuma
+    # Only support multiples of numa-factor or less than numa-factor
+    VALID_NODE_CONFIG=$(( ((${OCR_NUM_NODES}%${OCR_NUMA_FACTOR})==0) || (${OCR_NUM_NODES}<${OCR_NUMA_FACTOR}) ))
+    if [[ ${VALID_NODE_CONFIG} == 0 ]]; then
+        echo "error: only support OCR_NUM_NODES (${OCR_NUM_NODES}) that are multiples of OCR_NUMA_FACTOR (${OCR_NUMA_FACTOR})"
+        exit 3
+    fi
+
     if [ "${OCRRUN_OPT_ENVKIND}" == "CLE" ] && [ "${OCR_NODEFILE}" == "" ]; then
         # For CLE need to tweak the args when it's a local run
         OCR_MPI_OPTS+=" -N ${OCR_NUM_NODES} -n ${OCR_NUM_NODES}"
     elif [ "${OCRRUN_OPT_ENVKIND}" == "SLURM" ]; then
-        OCR_MPI_OPTS+=" -N ${OCR_NUM_NODES} -n ${OCR_NUM_NODES}"
+        # Get one process per numa domain per node
+        ACTUAL_NUM_PHYS_NODES=${OCR_NUM_NODES}
+        ACTUAL_NUM_PHYS_PROCESSES=$(( ${OCR_NUM_NODES} * ${OCR_NUMA_FACTOR} ))
+        OCR_MPI_OPTS+=" -N ${ACTUAL_NUM_PHYS_NODES} -n ${ACTUAL_NUM_PHYS_PROCESSES}"
     else
         OCR_MPI_OPTS+=" ${OCRRUN_OPT_NUM_NODES} ${OCR_NUM_NODES}"
     fi
 
     if [[ "${OCRRUN_GDB}" == "yes" ]]; then
         OCR_MPI_OPTS+=" ${OCRRUN_OPT_GDB}"
-    if [[ "${OCR_ASAN}" == "yes" ]]; then
-        export ASAN_OPTIONS=abort_on_error=1
-    fi
+        if [[ "${OCR_ASAN}" == "yes" ]]; then
+            export ASAN_OPTIONS=abort_on_error=1
+        fi
     fi
 
     if [[ "${OCRRUN_VALGRIND_OPTS}" != "" ]]; then
@@ -153,7 +173,7 @@ if [[ "$RES" != "" ]]; then
         OCRRUN_VTUNE_RESULTDIR=${OCRRUN_VTUNE_RESULTDIR-"${PROGPATH}/vtune-trace"} #"
         PROGRAM_BIN="amplxe-cl -collect ${OCRRUN_VTUNE_COLLECT} -trace-mpi -result-dir ${OCRRUN_VTUNE_RESULTDIR} ${PROGRAM_BIN}"
     fi
-
+    echo "${OCRRUN_OPT_CMD} ${OCR_MPI_OPTS} ${PROGRAM_BIN} -ocr:cfg ${OCR_CONFIG}"
     ${OCRRUN_OPT_CMD} ${OCR_MPI_OPTS} ${PROGRAM_BIN} -ocr:cfg ${OCR_CONFIG}
     RET_CODE=$?
 
@@ -163,7 +183,6 @@ if [[ "$RES" != "" ]]; then
             hpcprof-mpi -I . ${HPCSTRUCT} -o ${OCRRUN_HPCTOOLKIT_DB} ${OCRRUN_HPCTOOLKIT_MEAS}
         fi
     fi
-
 
     exit ${RET_CODE}
 fi
